nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R C.paca &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R C.olivaceus  &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R C.thous &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R C.unicinctus &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R D.imperfecta &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R D.kappleri &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R D.leporina &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R D.marsupialis &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R D.novemcinctus &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R E.barbara &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R H.hydrohaeris &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R L.pardalis &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R L.tigrinus &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R L.wiedii &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R M.americana &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R M.gouazoubira &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R M.pratti &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R M.tridactyla &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R N.nasua &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R O.virginianus &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R P.concolor &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R P.maximus &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R P.onca &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R P.tajacu &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R S.venaticus &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R T.pecari &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R T.terrestris &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R T.tetradactyla &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R T.major &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R L.rufaxilla &
nohup Rscript --vanilla $SCRIPTDIR/R/Occupancy_models/single_visit_models.R C.alector &
